core/urls.py
from django.urls import path
from core.views import (
	HomeView,
	ShopView,
	ProductDetailView,
	add_to_cart,
	remove_from_cart,
	remove_single_item_from_cart,
	CartView,
	CheckoutView,
	AddCouponView,
	PaymentView,
	BikashView,
	DbblView,
	contact_view,
	about_view,
	blog_view
)

app_name = 'core_main'

urlpatterns = [
    path('', HomeView.as_view(),name="home_view"),
    path('shop/', ShopView.as_view(),name="shop_view"),
    path('product_detail/<slug>/',ProductDetailView.as_view(),name="product_detail"),
    path('add_to_cart/<slug>/',add_to_cart,name="add_to_cart"),
    path('remove_from_cart/<slug>/',remove_from_cart,name="remove_from_cart"),
    path('remove_single_item_from_cart/<slug>/',remove_single_item_from_cart,name="remove_single_item_from_cart"),
    path('cart/',CartView.as_view(),name="cart"),
    path('checkout/',CheckoutView.as_view(),name="checkout"),
    path('add-coupon/',AddCouponView.as_view(),name="add-coupon"),
    path('payment_stripe/<payment_option>/',PaymentView.as_view(),name="payment"),
    path('payment_bikash/<payment_option>/',BikashView.as_view(),name="bikash"),
    path('payment_dbbl/<payment_option>/',DbblView.as_view(),name="dbbl"),
    path('contact/', contact_view),
    path('about/', about_view),
    path('blog/', blog_view),  
]

ecommerce_amazon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls',namespace='core_main')),
    #urls for django alluth........
   	path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% include 'head.html' %}
	{% block extra_head %}
	{% endblock %}
  <body>

	    {% include 'navbar.html' %}
	    
		{% if messages %}
		    <div class="mt-5 pt-4">
			    {% for message in messages %}
			       	<div class="alert alert-{{ message.tags }}" role="alert">
			          {{ message }}
			          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
			            <span aria-hidden="true">&times</span>
			          </button>
			        </div>
			      {% endfor %} 
	 		</div>
 		{% endif %}
			
		{% block content %}

		{% endblock %}

	    {% include 'footer.html' %}
	  

	  		<!-- loader -->
	  	<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

		{% include 'scripts.html' %}


		{% block extra_scripts %}
  		{% endblock %}
    
  </body>
</html>

templates/bikash_payment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<h1>type your number</h1>
{% endblock %}

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_6.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-0 bread">My Cart</h1>
            <p class="breadcrumbs">
              <span class="mr-2"><a href="index.html">Home</a>
              </span> <span>Cart</span>
            </p>
          </div>
        </div>
      </div>
    </div>
		
		<section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div class="cart-list">
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th>&nbsp;</th>
						        <th>&nbsp;</th>
						        <th>Product</th>
						        <th>Price</th>
						        <th>Quantity</th>
						        <th>Discount</th>
                    <th>Total</th>
						      </tr>
						    </thead>
						    <tbody>
                  {% for obj in object.items.all %}
						      <tr class="text-center">
						        <td class="product-remove">
                      <a href="{{obj.item.get_remove_from_cart_url}}">
                        <span class="ion-ios-close"></span>
                      </a>
                    </td>
						        
						        <td class="image-prod">
                      <div class="img" style="background-image:url({{obj.item.image.url}});"></div>
                    </td>
						        
						        <td class="product-name">
						        	<h3>{{ obj.item.title }}</h3>
						        	<p>Far far away, behind the word mountains, far from the countries</p>
						        </td>
  						        {% if obj.item.discount_price %}
  						          <td class="price">${{ obj.item.discount_price }}</td>
                      {% else %}
  						          <td class="price">${{ obj.item.price }}</td>
                      {% endif %}
  						        <td class="">
                        <a class="btn btn-primary" href="{{obj.item.get_remove_single_from_cart_url}}">
                          <span>-</span>
                        </a>                  
                          <span>{{ obj.quantity }}</span>
                        <a class="btn btn-primary" href="
                          {{obj.item.get_add_to_cart_url}}">
                          <span>+</span> 
                        </a>
					            </td>
                      <td class="total">${{ obj.get_amount_saved }}</td>
						        {% if obj.get_total_discount_item_price %}
						          <td class="total">${{ obj.get_total_discount_item_price }}</td>
                    {% else %}
                      <td class="total">${{ obj.get_total_item_price }}</td>
                    {% endif %}

						      </tr>
                  {% endfor %}
						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
    		<div class="row justify-content-end">
    			<div class="col col-lg-5 col-md-6 mt-5 cart-wrap ftco-animate">
    				<div class="cart-total mb-3">
    					<h3>Cart Totals</h3>
    					<hr>
              <p class="d-flex total-price">
                <span>Total</span>
                {% if object.get_total %}
                <span>${{ object.get_total }}</span>
                {% endif %}
              </p>	
    				</div>
    				<p class="text-center"><a href="/checkout/" class="btn btn-primary py-3 px-4">Proceed to Checkout</a></p>
    			</div>
    		</div>
			</div>
		</section>

		<section class="ftco-section-parallax">
      <div class="parallax-img d-flex align-items-center">
        <div class="container">
          <div class="row d-flex justify-content-center py-5">
            <div class="col-md-7 text-center heading-section ftco-animate">
            	<h1 class="big">Subscribe</h1>
              <h2>Subcribe to our Newsletter</h2>
              <div class="row d-flex justify-content-center mt-5">
                <div class="col-md-8">
                  <form action="#" class="subscribe-form">
                    <div class="form-group d-flex">
                      <input type="text" class="form-control" placeholder="Enter email address">
                      <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_6.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-0 bread">Checkout</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Checkout</span></p>
          </div>
        </div>
      </div>
    </div>
		
<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
         	<div class="col-xl-8 ftco-animate">
			<form method="POST" action="." class=" billing-form bg-light p-3 p-md-5">
				{% csrf_token %}
				<h3 class="mb-4 billing-heading">Shipping Address</h3>
	          	<div class="hideable_shipping_form row align-items-end">
                	<div class="w-100"></div>
                	
				    <div class="col-md-12">
				        <div class="form-group">
				           	<label for="country">State / Country</label>
				            <div class="select-wrap">
				                <div class="icon"><span class="ion-ios-arrow-down"></span></div>
						        {{forms.shipping_country}}
				            </div>
				        </div>
				    </div>
			        <div class="w-100"></div>
			        <div class="col-md-6">
			           	<div class="form-group">
		                	<label for="streetaddress">Street Address</label>
		                  	<input id="shipping_address" name="shipping_address" type="text" class="form-control" placeholder="House number and street name">
		                </div>
			        </div>
			        <div class="col-md-6">
			            <div class="form-group">
		                  	<input id="shipping_address2" name="shipping_address2" type="text" class="form-control" placeholder="Appartment, suite, unit etc: (optional)">
		                </div>
			        </div>
			        <div class="w-100"></div>
			        <div class="col-md-6">
			           	<div class="form-group">
		                	<label for="towncity">Town / City</label>
		                  	<input id="shipping_city" name="shipping_city" type="text" class="form-control" placeholder="">
		                </div>
			        </div>
			        <div class="col-md-6">
			            <div class="form-group">
			            	<label for="postcodezip">Postcode / ZIP *</label>
		                  	<input id="shipping_zip_code" name="shipping_zip_code" type="text" class="form-control" placeholder="">
		                </div>
			        </div>
			        <div class="w-100"></div>
			        <div class="col-md-6">
		                <div class="form-group">
		                	<label for="phone">Phone</label>
		                  	<input id="shipping_phone_number" name="shipping_phone_number" type="text" class="form-control" placeholder="">
		                </div>
		            </div>
		            <div class="col-md-6">
		                <div class="form-group">
		                	<label for="emailaddress">Email Address</label>
		                  	<input id="shipping_email_address" name="shipping_email_address" type="text" class="form-control" placeholder="">
		                </div>
	                </div>
                	<div class="w-100"></div>
	        	</div>
	        	<div class="col-md-12">
                	<div class="form-group mt-4">
						<div class="radio">
							<label class="mr-3">
								<input id="same_billing_address" type="checkbox" name="same_billing_address"> Same as Billing Address
								</label>
							<label>
								<input name="set_default_shipping" id="set_default_shipping" type="checkbox" name="">Save as default Shipping
							</label>
						</div>
					</div>

					{% if default_shipping_address %}
						<div class="form-group mt-1">
							<div class="radio">
								<label>
									<input id="set_default_shipping" type="checkbox" name="use_default_shipping">
									Use default Shipping: {{default_shipping_address.street_address|truncatechars:10 }}
								</label>
							</div>
						</div>
					{% endif %}
                </div>

				<hr>
	            <h3 class="mb-4 billing-heading">Billing Address</h3>
	          	<div class="hideable_billing_form row align-items-end">
                	<div class="w-100"></div>
			        <div class="col-md-12">
			            <div class="form-group">
			            	<label for="country">State / Country</label>
			            		<div class="select-wrap">
			                		<div class="icon"><span class="ion-ios-arrow-down"></span></div>
					                {{forms.billing_country}}
			                	</div>
			            	</div>
			         	</div>
		            <div class="w-100"></div>
		            <div class="col-md-6">
		            	<div class="form-group">
	                		<label for="billing_address">Street Address</label>
	                  		<input id="billing_address" name="billing_address" type="text" class="form-control" placeholder="House number and street name">
	                	</div>
		            </div>
		            <div class="col-md-6">
		            	<div class="form-group">
	                  <input name="billing_address2" type="text" class="form-control" placeholder="Appartment, suite, unit etc: (optional)">
	                </div>
		            </div>
		            <div class="w-100"></div>
		            <div class="col-md-6">
		            	<div class="form-group">
	                	<label for="towncity">Town / City</label>
	                  <input name="billing_city" type="text" class="form-control" placeholder="">
	                </div>
		            </div>
		            <div class="col-md-6">
		            	<div class="form-group">
		            	<label for="postcodezip">Postcode / ZIP *</label>
	                  	<input id="billing_zip_code" name="billing_zip_code" type="text" class="form-control" placeholder="">
	                </div>
		            </div>
		            <div class="w-100"></div>
		            <div class="col-md-6">
	                <div class="form-group">
	                	<label for="phone">Phone</label>
	                  <input name="billing_phone_number" type="text" class="form-control" placeholder="">
	                </div>
	              </div>
	              <div class="col-md-6">
	                <div class="form-group">
	                	<label for="emailaddress">Email Address</label>
	                  <input name="billing_email_address" type="text" class="form-control" placeholder="">
	                </div>
                </div>
                <div class="w-100"></div>
	        </div>

	        <div class="col-md-12">
                <div class="form-group mt-4">
                	{% if default_billing_address %}
						<div class="radio">
							<label>
								<input type="checkbox" name="use_default_billing"> Use default Billing: {{ default_billing_address.street_address|truncatechars:10 }}
							</label>
						</div>
					{% endif %}
					
				</div>
           	</div>
           	<hr>
           	<h3>PAYMENT OPTION</h3>
           	<hr>

           	{% for value, name in forms.fields.payment_option.choices %}

	           	<div class="form-group">
					<div class="col-md-12">
						<div class="radio">
							<label for="{{ name }}">
							<input  id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" name="optradio" class="mr-2">{{ name }}
							</label>
						</div>
					</div>
				</div>
			{% endfor %}
           	<button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
	    </form><!-- END -->
    </div> <!-- .col-md-8 -->
     <div class="col-xl-4 d-flex">
	    <div class="cart-detail  cart-total p-md-4">
	    	<div class="bg-light p-4">
	        {% for order_item in order.items.all %}
		        <h3 class="billing-heading mb-4">Cart Total</h3>
		        <p class="d-flex">
			    	<span>Subtotal</span>
			    	<span>${{ order_item.get_final_price }}</span>
			    </p>
			    <p class="d-flex">
			    	<span>Amount Saved</span>
			    	<span>${{ order_item.get_amount_saved }}</span>
			    </p>
		    {% endfor %}

		    {% if order.coupon %}
			    <p class="d-flex">
				   	<span>Promo code</span>
				    <span>{{ order.coupon.code }}</span>
				</p>
				<p class="d-flex">
				    <span>Promo Amount</span>
				    <span>-${{ order.coupon.amount }}</span>
				</p>
			{% endif %}
			{% if DISPLAY_COUPON_FORM %}
			    <form method="POST" action="{% url 'core_main:add-coupon' %}"  class="card p-2">
			    {% csrf_token %}
					<div class="input-group">				              
		                {{ couponform.code }}
					    <div class="input-group-append">
					        <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
					    </div>
					</div>
				</form>
			{% endif %}
		    <hr>
		    <p class="d-flex total-price">
		    	<span>Total</span>
		    	<span>${{ order.get_total }}</span>
		    </p>
		</div>
		</div>
	</div>
	        
    </div>  
    </div>
</section> <!-- .section -->

 

	<section class="ftco-section-parallax">
      <div class="parallax-img d-flex align-items-center">
        <div class="container">
          <div class="row d-flex justify-content-center py-5">
            <div class="col-md-7 text-center heading-section ftco-animate">
            	<h1 class="big">Subscribe</h1>
              <h2>Subcribe to our Newsletter</h2>
              <div class="row d-flex justify-content-center mt-5">
                <div class="col-md-8">
                  <form action="#" class="subscribe-form">
                    <div class="form-group d-flex">
                      <input type="text" class="form-control" placeholder="Enter email address">
                      <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}


{% block extra_scripts %}
  <script>
    var hideable_shipping_form = $('.hideable_shipping_form');
    var hideable_billing_form = $('.hideable_billing_form');

    var same_as_billing_shipping = document.querySelector("input[name=same_billing_address]");
   
    var use_default_shipping = document.querySelector("input[name=use_default_shipping]");

    var use_default_billing = document.querySelector("input[name=use_default_billing]");

    same_as_billing_shipping.addEventListener('change', function() {
      if (this.checked){
        hideable_billing_form.hide();
      }
      else{
        hideable_billing_form.show();
      }
    })

    use_default_shipping.addEventListener('change', function() {
      if (this.checked){
        hideable_shipping_form.hide();
      }
      else{
        hideable_shipping_form.show();
      }
    })

    use_default_billing.addEventListener('change', function() {
      if (this.checked){
        hideable_billing_form.hide();
      }
      else{
        hideable_billing_form.show();
      }
    })


  </script>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
		
		<div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_6.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-0 bread">Contact Us</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Contact</span></p>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section contact-section bg-light">
      <div class="container">
        <div class="row block-9">
          <div class="col-md-6 order-md-last d-flex">
            <form action="#" class="bg-white p-5 contact-form">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Name">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Email">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Subject">
              </div>
              <div class="form-group">
                <textarea name="" id="" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
              </div>
              <div class="form-group">
                <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
              </div>
            </form>
          
          </div>

          <div class="col-md-6 d-flex">
          	<div id="map" class="bg-white"></div>
          </div>
        </div>
        <div class="row d-flex mt-5 contact-info">
          <div class="w-100"></div>
          <div class="col-md-3 d-flex">
          	<div class="info bg-white p-4">
	            <p><span>Address:</span> 198 West 21th Street, Suite 721 New York NY 10016</p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="info bg-white p-4">
	            <p><span>Phone:</span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="info bg-white p-4">
	            <p><span>Email:</span> <a href="mailto:info@yoursite.com">info@yoursite.com</a></p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="info bg-white p-4">
	            <p><span>Website</span> <a href="#">yoursite.com</a></p>
	          </div>
          </div>
        </div>
      </div>
    </section>
		
		<section class="ftco-section-parallax">
      <div class="parallax-img d-flex align-items-center">
        <div class="container">
          <div class="row d-flex justify-content-center py-5">
            <div class="col-md-7 text-center heading-section ftco-animate">
            	<h1 class="big">Subscribe</h1>
              <h2>Subcribe to our Newsletter</h2>
              <div class="row d-flex justify-content-center mt-5">
                <div class="col-md-8">
                  <form action="#" class="subscribe-form">
                    <div class="form-group d-flex">
                      <input type="text" class="form-control" placeholder="Enter email address">
                      <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

templates/dbbl_payment.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="container mt-5 pt-5">
	<h1>This Is Our DBBL Number</h1>
	<img class="img-fluid" src="{% static 'images/dbbl.png' %}" alt="">
	<h2>+8801794021132</h2>
	<h2>+8801794021131</h2>
	<h2>+8801794021133</h2>
</div>

<section class="ftco-section-parallax">
    <div class="parallax-img d-flex align-items-center">
        <div class="container">
           	<div class="row d-flex justify-content-center py-5">
                <div class="col-md-7 text-center heading-section ftco-animate">
                	<h1 class="big">Subscribe</h1>
                    <h2>Subcribe to our Newsletter</h2>
                    <div class="row d-flex justify-content-center mt-5">
                      	<div class="col-md-8">
	                        <form action="#" class="subscribe-form">
	                          <div class="form-group d-flex">
	                            <input type="text" class="form-control" placeholder="Enter email address">
	                            <input type="submit" value="Subscribe" class="submit px-3">
	                          </div>
	                        </form>
                      	</div>
                    </div>
                </div>
            </div>
        </div>
     </div>
</section>



{% endblock %}

templates/footer.html
<footer class="ftco-footer bg-light ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Modist</h2>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-5">
              <h2 class="ftco-heading-2">Menu</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-2 d-block">Shop</a></li>
                <li><a href="#" class="py-2 d-block">About</a></li>
                <li><a href="#" class="py-2 d-block">Journal</a></li>
                <li><a href="#" class="py-2 d-block">Contact Us</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Help</h2>
              <div class="d-flex">
	              <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
	                <li><a href="#" class="py-2 d-block">Shipping Information</a></li>
	                <li><a href="#" class="py-2 d-block">Returns &amp; Exchange</a></li>
	                <li><a href="#" class="py-2 d-block">Terms &amp; Conditions</a></li>
	                <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
	              </ul>
	              <ul class="list-unstyled">
	                <li><a href="#" class="py-2 d-block">FAQs</a></li>
	                <li><a href="#" class="py-2 d-block">Contact</a></li>
	              </ul>
	            </div>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
						  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>
          </div>
        </div>
      </div>
    </footer>
    

templates/head.html
{% load static %}
<head>
    <title>Modist</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">

    
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>

templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	<div class="container">
	    <a class="navbar-brand" href="index.html">Modist</a>
	    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	    </button>

	    <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	        	<li class="nav-item active">
	          		<a href="/." class="nav-link">Home</a>
	        	</li>
	          	<li class="nav-item dropdown">
              		<a href="/shop" class="nav-link">Shop</a>
           		</li>
	        	<li class="nav-item">
	        		<a href="/about" class="nav-link">About</a>
	        	</li>
	        	<li class="nav-item">
	        		<a href="/blog" class="nav-link">Blog</a>
	        	</li>
	        	<li class="nav-item">
	        		<a href="/contact" class="nav-link">Contact</a>
	        	</li>
	        	{% if request.user.is_authenticated %}
	        		<li class="nav-item cta cta-colored">
	        			<a href="{% url 'core_main:cart' %}" class="nav-link">
	        				<span class="icon-shopping_cart"></span>[{{ request.user|cart_item_count }}]
	        			</a>
	        		</li>
	        		<li class="nav-item">
	        			<a href="{% url 'account_logout' %}" class="nav-link">Logout</a>
	        		</li>
	        	{% else %}
					<li class="nav-item">
	        			<a href="{% url 'account_login' %}" class="nav-link">Login</a>
	        		</li>
	        		<li class="nav-item">
	        			<a href="{% url 'account_signup' %}" class="nav-link">SignUp</a>
	        		</li>
	        	{% endif %}
	        </ul>
	    </div>
	</div>
</nav>
    <!-- END nav -->